
### nginx/default.conf
server {
    listen 80; // Escuta na porta 80

    location / {
        root /usr/share/nginx/html; // Diretório raiz dos arquivos estáticos
        index index.html; // Arquivo principal
    }

    location /api/ {
        proxy_pass http://node_app:3000/; // Redireciona chamadas para o backend Node.js
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
